#!/bin/bash
compiler=clang++
flags="--std=c++14 -O2 -g -ggdb -Wall -Wextra"
files=(main tests)
for i in ${files[@]}; do
    $compiler -c $i.cpp $flags
done
$compiler ${files[@]/%/.o}
rm ${files[@]/%/.o}
